name: Build and Push Docker image to GitHub Container Registry

on:
  push:
    branches:
      - main  # Chạy workflow này khi có sự thay đổi trên nhánh chính (main)
  pull_request:
    branches:
      - main  # Chạy workflow khi có pull request vào nhánh chính

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Sử dụng GITHUB_TOKEN mặc định
      - name: Set up java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}